services:
  app:
    build:
      context: .
      target: base
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      RUN_DB_MIGRATION: "false"
      LOG_PRETTY: "true"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  scheduler:
    build:
      context: .
      target: base
    command: sh -c "npm install && npm run scheduler"
    environment:
      NODE_ENV: development
      RUN_DB_MIGRATION: "false"
      LOG_PRETTY: "true"
    volumes:
      - .:/app
      - /app/node_modules

